Areas/Admin/Controllers/BrandAController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using comestic_csharp.Models;
using Microsoft.AspNetCore.Authorization;
using comestic_csharp.Areas.Identity.Data;

namespace comestic_csharp.Controllers
{
    [Authorize(Roles ="admin")]
    [Area("admin")]
    [Route("admin/brand")]
    public class BrandAController : Controller
    {
        private readonly ShopDbContext _context;

        public BrandAController(ShopDbContext context)
        {
            _context = context;
        }

        [Route("index")]// GET: Brand
        public async Task<IActionResult> Index()
        {
            return View(await _context.Brands.ToListAsync());
        }

        // GET: Brand/Details/5
        public async Task<IActionResult> Details(ulong? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // GET: Brand/Create
        [Route("create")]// GE
        public IActionResult Create()
        {
            return View();
        }

        // POST: Brand/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        
        [Route("create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Slug,Status")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                _context.Add(brand);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        // GET: Brand/Edit/5
        [Route("edit")]
        public async Task<IActionResult> Edit(ulong? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands.FindAsync(id);
            if (brand == null)
            {
                return NotFound();
            }
            ViewData["Status"] = new SelectList(

                 new List<SelectListItem>
                {
                    new SelectListItem { Text = "active", Value = "active"},
                    new SelectListItem { Text = "inactive", Value = "inactive"},
                }, "Value" , "Text",brand.Status

            );
            return View(brand);
            
        }

        // POST: Brand/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("edit")]
        public async Task<IActionResult> Edit(ulong id, [Bind("Id,Title,Slug,Status")] Brand brand)
        {
            if (id != brand.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(brand);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrandExists(brand.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                
                return RedirectToAction(nameof(Index));
            }
            ViewData["Status"] = new SelectList(

                 new List<SelectListItem>
                {
                    new SelectListItem { Text = "active", Value = "active"},
                    new SelectListItem { Text = "inactive", Value = "inactive"},
                }, "Value" , "Text",brand.Status

            );
            return View(brand);
        }

        // GET: Brand/Delete/5
         [Route("delete")]
        public async Task<IActionResult> Delete(ulong? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // POST: Brand/Delete/5
        [Route("delete")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(ulong id)
        {
            var brand = await _context.Brands.FindAsync(id);
            _context.Brands.Remove(brand);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BrandExists(ulong id)
        {
            return _context.Brands.Any(e => e.Id == id);
        }
    }
}

Areas/Admin/Views/BrandA/Create.cshtml
@model comestic_csharp.Models.Brand


        <!-- [ breadcrumb ] start -->
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">BRAND</h5>
                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a class="pc-link" asp-action="index" asp-controller="Dashboard">Home</a></li>
                            <li class="breadcrumb-item"><a class="pc-link" asp-action="index" asp-controller="BrandA">Brand</a></li>
                            <li class="breadcrumb-item">Create Brand</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ breadcrumb ] end -->
        <!-- [ Main Content ] start -->
        <div class="pcoded-content">

                <!-- [ form-element ] start -->
                    <div class="card">
                        <form asp-action="Create">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="card-header">
                                <h3><mark>Create New Brand</mark></h3>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label asp-for="Title" class="control-label"></label>
                                    <input asp-for="Title" class="form-control" />
                                    <span asp-validation-for="Title" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Slug" class="control-label"></label>
                                    <input asp-for="Slug" class="form-control" />
                                    <span asp-validation-for="Slug" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="card-footer">
                                <input type="submit" value="Create" class="btn btn-primary" />
                                <a asp-action="Index" class="btn btn-primary">Back to List</a>
                            </div>
                        </form>
                    </div>
                <!-- [ form-element ] end -->
            <!-- [ Main Content ] end -->
        </div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/BrandA/Delete.cshtml
@model comestic_csharp.Models.Brand

@{
    ViewData["Title"] = "Delete";
}

<div class="pcoded-content">
    <div class = "card">
        <div class="card-body">
            <h5 class="card-title">Are you sure you want to delete this?</h5>
            <h4>Banner</h4>
            <hr />
            <dl class="row">
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Title)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Title)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Slug)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Slug)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Status)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Status)
                </dd>
            </dl>
        </div>
        <div class="card-footer">
            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Delete" class="btn btn-danger" />
                <a asp-action="Index" class="btn btn-primary" >Back to List</a>
            </form>
        </div>
    </div>
</div>

Areas/Admin/Views/BrandA/Details.cshtml
@model comestic_csharp.Models.Brand

@{
    ViewData["Title"] = "Details";
}
 <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">BRAND</h5>
                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a class="pc-link" asp-action="index" asp-controller="Dashboard">Home</a></li>
                            <li class="breadcrumb-item"><a class="pc-link" asp-action="index" asp-controller="BrandA">Brand</a></li>
                            <li class="breadcrumb-item">Details BRAND</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

<div class="pcoded-content">
    <div class="card">
        <h3 class="card-header">Details</h3>
        <div class="card-body">
            <dl class="row">
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Title)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Title)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Slug)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Slug)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Status)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Status)
                </dd>
            </dl>
        </div>
        <div class="card-footer">
            <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-outline-warning">Edit</a>
            <a asp-action="Index" class="btn btn-outline-primary" >Back to List</a>
        </div>
    </div>
</div>

Areas/Admin/Views/BrandA/Edit.cshtml
@model comestic_csharp.Models.Brand

@{
    ViewData["Title"] = "Edit";
}

        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">BRAND</h5>
                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a class="pc-link" asp-action="index" asp-controller="Dashboard">Home</a></li>
                            <li class="breadcrumb-item"><a class="pc-link" asp-action="index" asp-controller="BrandA">Brand</a></li>
                            <li class="breadcrumb-item">Edit Brand</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>


<div class="pcoded-content">
            <div class="card">
                <div class="col-md-4">
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="Id" />
                        <h3 class="card-header">EDIT Brand</h3>
                        <div class="card-body">
                            <div class="form-group">
                                <label asp-for="Title" class="control-label"></label>
                                <input asp-for="Title" class="form-control" />
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Slug" class="control-label"></label>
                                <input asp-for="Slug" class="form-control" />
                                <span asp-validation-for="Slug" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Status" class="control-label"></label>
                                <select asp-for="Status" class ="form-control" asp-items="ViewBag.Status"></select>
                                <span asp-validation-for="Status" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="card-footer">
                                <input type="submit" value="Save" class="btn btn-primary" />
                                <a asp-action="Index" class="btn btn-primary">Back to List</a>
                        </div>
                    </form>
                </div>
            </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/BrandA/Index.cshtml
@model IEnumerable<comestic_csharp.Models.Brand>

@{
    ViewData["Title"] = "Index";
}

@await Html.PartialAsync("_StyleLayout")
<link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>

<div class="page-header">
        <div class="page-block">
            <div class="row align-items-center">
                <div class="col-md-12">
                    <div class="page-header-title">
                        <h5 class="m-b-10">BRAND</h5>
                    </div>
                    <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a class="pc-link" asp-action="index" asp-controller="Dashboard">Home</a></li>
                            <li class="breadcrumb-item"><a class="pc-link" asp-action="index" asp-controller="BrandA">Brand</a></li>
                            <li class="breadcrumb-item">Index</li>
                    </ul>
                    </div>
                </div>
        </div>
</div>

<div class="pcoded-content">
   <section class="content">
      <div class="container-fluid">        
        <div class="row">
          <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-9">
                                <h3 class="card-header">BRAND</h3>       
                            </div>
                            <div class="col-3">
                                <p class="card-header" style="margin-top: 11px !important"><a asp-action="Create" class="add"><i data-feather ="plus"></i> Add new</a></p>
                            </div>
                        </div>
                    </div>
                <!-- /.card-header -->
                    <div class="card-body">
                        <table class="table" id="example1" >
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Title)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Slug)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Status)
                                        </th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach (var item in Model) {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Title)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Slug)
                                        </td>
                                        <td>
                                             @if( item.Status =="active") {
                                              
                                                <input type="checkbox"  checked data-toggle="toggle" data-size="sm" data-on="Active" data-off="Inactive" data-onstyle="outline-success" data-offstyle="outline-danger" style="padding-left: 8px !important;">
                                           }
                                           else{
                                                <input type="checkbox"  data-toggle="toggle" data-size="sm" data-on="Active" data-off="Inactive" data-onstyle="outline-success" data-offstyle="outline-danger" style="padding-left: 8px !important;">
                                           }
                                        </td>
                                        <td>
                                            <a asp-action="Edit" asp-route-id="@item.Id"><i data-feather ="edit" style="color: #3EC9E6;"></i></a> 
                                            <a asp-action="Details" asp-route-id="@item.Id"><i data-feather ="eye"></i></a> 
                                            <a asp-action="Delete" asp-route-id="@item.Id"><i data-feather="trash" style="color: red;"></i></a>
                                        </td>
                                    </tr>
                                }   
                                </tbody>
                        </table>
                    </div>
                <!-- /.card-body -->
                </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
</div>
  
@await Html.PartialAsync("_ScriptsLayout")

Areas/Admin/Views/BrandA/Index_goc.cshtml
@model IEnumerable<comestic_csharp.Models.Brand>

@{
    ViewData["Title"] = "Index";
}

<div class="page-header">

        <div class="page-block">
            <div class="row align-items-center">
                <div class="col-md-12">
                    <div class="page-header-title">
                        <h5 class="m-b-10">BRAND</h5>
                    </div>
                    <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a class="pc-link" asp-action="index" asp-controller="Dashboard">Home</a></li>
                            <li class="breadcrumb-item"><a class="pc-link" asp-action="index" asp-controller="BrandA">Brand</a></li>
                            <li class="breadcrumb-item">Index</li>
                    </ul>
                    </div>
                </div>
        </div>
</div>

<div class="pcoded-content">
    <div class="card">
            <div class="flex-container">
    <div><h1 style="text-align: center; color: #095a3c; padding-top: 30px; padding-left: 40px">Brand</h1></div>
    <div></div>
    <div><p><a asp-action="Create" class="add"><i data-feather ="plus"></i>  Add new</a></p></div> </div>

        <table class="table" >
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Slug)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Status)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Slug)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id"><i data-feather ="edit" style="color: #3EC9E6;"></i></a> 
                        <a asp-action="Details" asp-route-id="@item.Id"><i data-feather ="eye"></i></a> 
                        <a asp-action="Delete" asp-route-id="@item.Id"><i data-feather="trash" style="color: red;"></i></a>
                    </td>
                </tr>
            }   
            </tbody>
        </table>
    </div>
</div>